### ISSUE TITLE
WPF UI should not use static positioning of elements

### ISSUE THREAD

**Issue by bragma** [NetSparkleUpdater/NetSparkle#109]
Some dialogs have problems if buttons have styles applied. As an example, I am using material style buttons and this is the result:

![image](https://user-images.githubusercontent.com/1101058/85113692-fd301480-b217-11ea-800b-3ae0efe33f2d.png)

This is because The "Remind me Later" button is positioned on the left of the "Download" button with a static margin value. This does not work if the final size of the button is not the expected value. It would be better to use a DockPanel instead.
If ok I'll work on a PR for this

**Comment by Deadpikle** [comment]
I went ahead and did this since I had some time today. I used a `StackPanel` instead since I think (?) that's a little simpler than a full DockPanel. This change is available in `2.0.0-preview20200621001`.

(If there are further issues, please feel free to open a PR after filing a bug.)

Thank you for the report! :)
