### ISSUE TITLE
[Question] Are revert supported?

### ISSUE THREAD

**Issue by kirsan31** [NetSparkleUpdater/NetSparkle#118]
Hi. Can't find info - are revert to previous (more then previous) version supported?

**Comment by Deadpikle** [comment]
Hi @kirsan31! 

The answer is both yes and no. No, because that is not the _default_ behavior. Yes, because if you use installers for each of your versions, you can use your app cast to see which previous versions are available and download those versions.

**Comment by Deadpikle** [comment]
Hi @kirsan31!

Sorry about the close and reopen -- I got some water on my trackpad and accidentally closed it when I cleaned it off. 😅 

The answer is both yes and no. No, because that is not the default behavior. Yes, because if you use installers for each of your versions, you can use your app cast to see which previous versions are available and download those versions. If your installers are standalone, they should install an old version just fine. Just keep in mind that if you install an old version and then there is a newer version in your app cast, after opening the older software, it will ask them if they want to update to the newer version!

Here's a summary of what you can do:

1. Setup your `SparkleUpdater` object
2. Call `_updateInfo = await _sparkle.CheckForUpdatesQuietly();` (no UI) or `_sparkle.CheckForUpdatesAtUserRequest()` (shows UI). I would recommend checking quietly because the UI method will always show the latest version. You can always show your own UI.
3. Look in `_updateInfo.Updates` for the available versions in your app cast. You can compare it with your currently installed version to see which ones are new and which ones are old.
4. Call `await _sparkle.InitAndBeginDownload(update);` with the update you want to download. The download path is provided in the `DownloadFinished` event.
5. When it's done downloading, call `_sparkle.InstallUpdate(update, _downloadPath);`

The "Handle Events Yourself" sample will be very helpful to you: https://github.com/NetSparkleUpdater/NetSparkle/tree/develop/src/NetSparkle.Samples.HandleEventsYourself

I hope that helps!

**Comment by brutalzinn** [comment]
Hello. Thank you very much for this library. I am trying to implement this in my application .. and I am very confused on some points.

I'm trying to follow the guidelines answered
 question in this:
https://github.com/NetSparkleUpdater/NetSparkle/issues/118#issue-660694626

but I’m stuck on creating the custom form. I need to list all the versions available for download .. but the
await mySparkleinstance.CheckForUpdatesQuietly()
returns null when the user skips an update.

**Comment by Deadpikle** [comment]
Closing this as the FAQ in the main README will contain the information from here.
