### ISSUE TITLE
DSAChecker.VerifySignatureOfFile() needs to catch errors

### ISSUE THREAD

**Issue by anti-matter** [NetSparkleUpdater/NetSparkle#124]
In production we are seeing a lot of crash reports here. 100% of the time the unhandled exception is caused by the downloaded installer file be held open for some reason. So, when called in `SparkleUpdater.InitAndBeginDownload()` the exception causes a crash of the app.

The fix, I believe is to wrap the file calls in a try/catch block and return `ValidationResult.Invalid` if the file cannot be opened. This way at least a re-download will be attempted and if _that_ fails, an error path is followed.

`    public ValidationResult VerifySignatureOfFile(
      string signature,
      string binaryPath)
    {
      using (Stream stream = (Stream) File.OpenRead(binaryPath))
        return this.VerifySignature(signature, Utilities.ConvertStreamToByteArray(stream));
    }
`

I worked around the issue for now by creating my own `ISignatureVerifier` class based on the `DSAChecker` class where the only difference is try/catch noted above.

**Comment by Deadpikle** [comment]
@anti-matter Hi! Thanks for the bug report. Instead of fixing this in the signature verifiers, I did this try/catch in `SparkleUpdater` instead so that all `ISignatureVerifier` types would have their errors caught. The exception is logged via `LogWriter`.

You don't happen to know if the root cause is some antivirus software running or something, do you? O_o

In any case, thanks for the report, and you can use `2.0.0-preview20200906001` once the CI/CD finishes

**Comment by Deadpikle** [comment]
Better yet, use `2.0.0-preview20200906002` and then you'll have an event called `DownloadedFileThrewWhileCheckingSignature` that will be called if the signature verifier throws while verifying a signature after download. :) 

....it's not a perfect solution, but I'm trying not to have any more seriously breaking changes between now and 2.0.
