### ISSUE TITLE
App cast generator: Add option to re-parse existing app cast and add (only?) new items rather than recreate entire app cast

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#167]
This would allow you to use CI/CD more easily by retaining your full history without having to get the signatures again for old binaries.

Probably would need to add a new flag to the app cast generator to this that defaulted to `false`.

**Comment by johncclayton** [comment]
Yep.  This begins to treat the appcast.xml as a current "source of truth"; I like that - and it would massively reduce the amount of data that needs to be pulled during delivery when re-building the appcast because there would be no need to re-calculate the signatures.

In terms of making it possible to generate the latest version from a GitHub Action I very much like this.  It does conflict with the --binaries command line option where the intent is to provide a set of binaries; would you see a need to ensure that the flags are not used together?

**Comment by Deadpikle** [comment]
Testable version in #270. Haven't tested it yet -- wrote the code and ran out of time. Needs testing. Still need to make sure conflicting options are not used. `--binaries` just sets the dir so that is fine, but I need to look at other options.

**Comment by johncclayton** [comment]
Awesome - I’ll give it a shot today if I get a chance :-)

**Comment by johncclayton** [comment]
There is a small problem - the code that runs the Parse() should first load the document from disk.  The 1 liner patch would be: 

                     Console.WriteLine("Parsing existing app cast at {0}...", appcastFileName);
-                    XDocument doc = XDocument.Parse(appcastFileName);
+                    var contents = File.ReadAllText(appcastFileName);
+                    XDocument doc = XDocument.Parse(contents);

What's the best way to submit a patch  -in the spirit of doing this myself once (instead of just talking about it).  Create a fork of the repo, patch the line - retest etc and then PR against this repo?  

After I added the change, I tested by taking an existing app XML file and .sig file along with a single .exe binary; then:
- tested that the existing binary is detected
- tested that a new binary gets added
- verified (using --verify and --signature) that the resulting appcast.xml seems valid. 

Let me know how I should throw the patch over to ya.

THANK YOU!

**Comment by Deadpikle** [comment]
Hahaha, this is what happens when one doesn't have time to test! Good catch.

You can fork, patch the line, then PR against #270 itself rather than the `develop` branch. If you don't get to it before I do, I can always add you as a co-author on the commit.

Thank you for testing and for responding back!
