### ISSUE TITLE
App cast generator null reference

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#173]
Got this in my email:

> I am trying to use the AppCastGenerator with a c# project. It finds my exe without issue - but continues to complain with "Object reference not set to an instance of an object." no matter what I do. I used it successfully to generate keys, but when I try to create the AppCast file, I get this error. Any ideas?

**Comment by Deadpikle** [comment]
More info:

> It looks like it was complaining because I didn't supply a base URL. I'll supply one and see if that helps.

Need to test this out and error out instead of obscure exceptions.

**Comment by WaseemAlkurdi** [comment]
I can confirm that this happened with me as well - it just throws a null object reference exception. For reference, I'm running on Windows, using the last version of the prebuilt (and now deprecated) commandline tools (since I'm unable to download a more modern Visual Studio release to compile this from source due to bandwidth constraints).

**Comment by WaseemAlkurdi** [comment]
Confirming this also happens on Linux as well.

**Comment by WaseemAlkurdi** [comment]
Also confirming that adding a base URL works, and that I need to work on my reading comprehension :-D

**Comment by Deadpikle** [comment]
@WaseemAlkurdi  Thanks for the confirmation! This bug is fixed, and it's rolling out via CI/CD now.

Can you use `dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator --version 2.0.1` to install the latest version? (In a few minutes when the CI/CD finishes and NuGet processes stuff.) You shouldn't have to build from source.

Otherwise, here's a zip of the latest build for you since I don't have it auto-publishing to the releases section on GitHub, if this is helpful: 
[app cast gen 2.0.1.zip](https://github.com/NetSparkleUpdater/NetSparkle/files/6178637/app.cast.gen.2.0.1.zip)

**Comment by WaseemAlkurdi** [comment]
@Deadpikle Appreciated! :)

I can't use the `dotnet` command since I'm intentionally keeping the VM offline to avoid using up my limited data cap on Windows updates (and therefore, connecting it without updates would expose my host and guest to malware).

I've tried this package, and unfortunately, I got this error:
```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\Waseem\Downloads\app.cast.gen.2.0.1\publish\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=5.0.4
  ```

Trying to copy `hostfxr.dll` from the extracted NuGet package of the final (unsupported) release of the tools package results in another error:
```
Failed to load the dll from [C:\Users\Waseem\Downloads\app.cast.gen.2.0.1\publish\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Users\Waseem\Downloads\app.cast.gen.2.0.1\publish\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```

I think that installing .NET 5.x would solve it, but since it might be self-contained (and it did mention things about self-containment) I thought I might want to tell you about the error first.

**Comment by Deadpikle** [comment]
Yeah, the thing I uploaded is definitely not self contained, so those errors are essentially expected.

If you can't install the .NET 5.x runtime on the VM, let me know and I'll get around to uploading a self-contained version for you sometime soon.

**Comment by WaseemAlkurdi** [comment]
@Deadpikle 

Installed .NET 5.0.4 Runtime, and it works just fine ... thanks for fixing this!

**Comment by mojo-man** [comment]
Thanks so much for fixing! Finally getting round to integrating things today.
