### ISSUE TITLE
Our method for executing the shell script on Unix is probably not going to work everywhere

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#191]
https://github.com/NetSparkleUpdater/NetSparkle/blob/5b0a74b06ce1cc446f2ea32aaf9fc9f2643e85b3/src/NetSparkle/SparkleUpdater.cs#L1437-L1460

`/bin/bash` being hard coded is probably a terrible idea for some systems. Need to find a better way to execute the shell script or find the bash location or something.

**Comment by SeanAWalsh** [comment]
From memory, the unix shell you're using ("/bin/bash", "/bin/sh") by convention is defined in the environment variable "SHELL". Just checked my SmoothWall firewall and there it was (SHELL=/bin/bash). Not sure if it's a hard and fast rule but I don't think I've never seen a Unix system where it wasn't!

So maybe NetSparkle could check for the environment variable SHELL. If there, use it, otherwise default to "/bin/sh"? I'm pretty sure it's guaranteed to be on every Unix system. Other shells aren't always there (BDS Unix /bin/csh, Korn shell ksh), think the bash shell has its root in Linux and GNU distributions and it's pretty widespread nowadays but I'm pretty sure that it's an absolute MUST that the Bourne shell (/bin/sh) HAS to be there (at least since 1979 when it became the superset of the original Thompson shell) or it just ain't Unix!

I don't see anything NetSparkle does that a standard Bourne shell (/bin/sh) can't handle. So we're not using any of the "shebang" of the other shell extensions so maybe just default to "/bin/sh"? Should always work.

**Comment by Deadpikle** [comment]
Thanks for your great suggestion and for your knowledge. I've implemented things as you've suggested. Thank you!
