### ISSUE TITLE
Windows 11 support

### ISSUE THREAD

**Issue by brads55** [NetSparkleUpdater/NetSparkle#220]
Hi,

When using NetSparkle with the WinForms .NetCore UI on the windows 11 preview, an available update causes the following crash:

```
Exception has occurred: CLR/System.Threading.ThreadStateException
An exception of type 'System.Threading.ThreadStateException' occurred in System.Windows.Forms.dll but was not handled in user code: 'ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.'
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   at NetSparkleUpdater.UI.WinForms.UpdateAvailableWindow.InitializeComponent()
   at NetSparkleUpdater.UI.WinForms.UpdateAvailableWindow..ctor(SparkleUpdater sparkle, List`1 items, Icon applicationIcon, Boolean isUpdateAlreadyDownloaded, String releaseNotesHTMLTemplate, String additionalReleaseNotesHeaderHTML)
   at NetSparkleUpdater.UI.WinForms.UIFactory.CreateUpdateAvailableWindow(SparkleUpdater sparkle, List`1 updates, Boolean isUpdateAlreadyDownloaded)
   at NetSparkleUpdater.SparkleUpdater.<>c__DisplayClass125_0.<ShowUpdateAvailableWindow>b__2(Object state)
   at NetSparkleUpdater.SparkleUpdater.<>c__DisplayClass125_1.<ShowUpdateAvailableWindow>b__3(Object state)
```

(The same code works fine on windows 10).

I believe this is possibly because the removal of internet explorer in windows 11 is causing the WebBrowser control to break in an unpredictable manner. It would be great to move this control over to something more modern that will work going forwards, such as WebView2.

**Comment by Deadpikle** [comment]
👋🏻  Does it happen if you add `[STAThread]`  to your `Main`? (If it's not already there by default.)

I'm not opposed to get something working with `WebView2`, but the normal `WebBrowser` control *should* still work: https://github.com/MicrosoftEdge/WebView2Feedback/issues/440#issuecomment-861643864. `WebView2` sounds nice, but backwards compatibility could be an issue, especially because "WebView2 requires a separate WebView2 Browser Runtime that has to be explicitly installed on a target machine" ([source](https://weblog.west-wind.com/posts/2021/Jan/14/Taking-the-new-Chromium-WebView2-Control-for-a-Spin-in-NET-Part-1)) and I don't want to distribute the runtime with NetSparkleUpdater for such a small part of the library's functionality.

Given that Windows 11 is very much in pre-release right now, I'm not going to take a look into this at the moment until we are closer to release.

Or, you may have found a race condition, and a repro would be very much appreciated.

Contributions are welcome.

**Comment by brads55** [comment]
I do already have `[STAThread]` on Main and as far as I can tell the control is being created on the main thread.

That comment is interesting, it's entirely possible that I've actually hit a bug in windows 11 here rather than an unsupported control. I'll dig into this a bit deeper when I get time and post more info here when I have it.

**Comment by brads55** [comment]
Turns out this was a mistake on my part, I'd actually hit https://github.com/dotnet/roslyn/issues/22112, what I thought worked on windows 10, actually didn't... Sorry for the noise!
