### ISSUE TITLE
Missing screenshot examples of Avalonia UI

### ISSUE THREAD

**Issue by Morasiu** [NetSparkleUpdater/NetSparkle#222]
It would be nice to see how the default NetSparkle UI for Avalonia looks like. I couldn't find any of it

**Comment by Deadpikle** [comment]
Here's a GIF. I don't want to commit to screenshots here since it's really simple to clone the repo and run the samples and keeping those screenshots for all operating systems and themes up to date is, well, annoying. :)

Very plain UI, in other words. Uses the default light theme. Looks just like WPF's UI. The changelog for Avalonia needs UI work, but it functions ok.

Keep in mind that you can easily override the Avalonia UI with your own for things like using the Fluent theme, dark theme, etc.

![avalonia-ui](https://user-images.githubusercontent.com/5092399/124835230-fec99900-df4e-11eb-9979-228b70528b42.gif)

Thanks for your question and for using NetSparkle!
