### ISSUE TITLE
Question about the signatures

### ISSUE THREAD

**Issue by idan-h** [NetSparkleUpdater/NetSparkle#256]
Hi!  
I glanced upon the signature code, and I have seen that the public key of the downloaded file comes from the request to the server - if I understood correctly.   
Doesn't that mean that a potential attacker can change the public key aswell as the downloaded file and hence pass the check?

Thank you!

**Comment by Deadpikle** [comment]
Hi @idan-h,

Thanks for your question.

The private key is what is important, here, and it's held by you or your development team. Without this key, a potential hacker will not be able to generate the appropriate signature(s) on the download server and thus get around the signature checks. The public key is only used to verify the signatures generated via the private key.

I think if an attacker has the ability to replace your app cast and your downloadable files, you have some other potential problems. 😄 

There are three or four pieces at play, here:

* Public key, shipped with your app
* Private key, held by you and your team and not to be leaked under basically any circumstance
* **Signature** of the downloaded installer file/update (inside the app cast)
* **Signature** of the app cast (this is not required and is the extra file that is downloaded (`appcast.xml.signature`)

The private key is used to generate the signatures, which are uploaded to your server or wherever. The public key is used to verify the authenticity of the signatures. If the public key of some download was changed, the authenticity check of the signatures would not work. If the download was changed on the server, again, the authenticity check would not work.

In order to get around things, a hacker would have to:

* Have your private key in order to generate signatures
* Have control over your application to replace the public key with their own as well as redirect to a different download(s)

In either circumstance, you have problems that are outside the scope of this library. In the first, you or your development team has leaked what is essentially a credential of some kind that shouldn't be leaked. In the second, you have a hacker replacing information in your binary and then redistributing that binary to your clients. A hacker cannot arbitrarily replace the files on your server and have them work as downloadable updates without the private key or without replacing the public key in your application.

For more information on public key cryptography, please see: https://en.wikipedia.org/wiki/Public-key_cryptography.

Hope that helps! :)

**Comment by idan-h** [comment]
Thank you for your explanation, it helped indeed.  
I meant that the hacker would exploit a Man In The Middle attack of some kind.  
  
So just for my clarification, the public key needs to be shipped with the binary that does the update, and the signature made from the private key is shipped with the appcast. Then, the signature is verified by the public key. Is that correct?  
  
What are the advantages of this against calling WinVerifyTrust from win32 api? That you don't need a code signing certificate and can make a self signed one?

**Comment by Deadpikle** [comment]
> Man In The Middle attack

Ah...I see. Yeah, without your private key to generate the appropriate signatures and without replacing your public key, I'm not sure how they could get this working.

> So just for my clarification, the public key needs to be shipped with the binary that does the update, and the signature made from the private key is shipped with the appcast. Then, the signature is verified by the public key. Is that correct?

Yes! :)

> What are the advantages of this against calling WinVerifyTrust from win32 api? That you don't need a code signing certificate and can make a self signed one?

Well...I don't know a lot about WinVerifyTrust. NetSparkleUpdater's method is cross platform; anything from win32 would not be for obvious reasons. NeteSparkleUpdater doesn't rely on any certificate chain, so no, you don't need a code signing certificate.

The method for verifying these signatures has been battle-tested for a long, long time via the macOS [Sparkle library](https://github.com/sparkle-project/Sparkle). 

I found a helpful quote [here at this SO post about WinVerifyTrust](https://stackoverflow.com/questions/1072540/winverifytrust-to-check-for-a-specific-signature):

> WinVerifyTrust will tell you the file is valid if any of the signatures are valid and come from a trusted certificate chain.

So...I think it has some sort of integration with Window's certificate chain / other mechanisms to make it work. I think that since it uses certificates, there's a similar public/private key mechanism floating around between WinVerifyTrust and NetSparkleUpdater. 

> Software Publisher Trust Provider can verify that an executable image file comes from a trusted software publisher and that the file has not been modified since it was published. [source](https://docs.microsoft.com/en-us/windows/win32/api/wintrust/nf-wintrust-winverifytrust#remarks)

So this may be tied into windows executable signing, too.

----

But to repeat, I don't know a lot about WinVerifyTrust, so can't really speak to it. I might argue that NetSparkleUpdater's method is easier to use. 😉 

There's nothing really stopping you from doing extra verification on your end, of course.

**Comment by idan-h** [comment]
I actually think that the sparkle way is more versatile and easy, as you don't have to acquire a code signing certificate in order to use it (plus as you said, it is cross platform).   
Thanks again for your informative answers, I found great value in them.
