### ISSUE TITLE
AppCast troubles

### ISSUE THREAD

**Issue by mylastsong18** [NetSparkleUpdater/NetSparkle#267]
Hello. I am trying to add update functionality to my application and have ran into a wall. I've tried everything i can think of and i am still having the same issue. 

Upon checking for downloads or launching the app i get this error in Visual Studio output

netsparkle: Appcast is not valid
netsparkle: No version information in app cast found

I generated the AppCast with the tool as per the readme. I did use the installer to generate it, maybe there is where my mistake is? I've tried editing the version value manually and have not been able to get passed this error. Can someone give me a hint at what could possibly be wrong? I have the following line in my AppCast so i don't understand why it isn't reading it

sparkle:version="1.0.484.0"

**Comment by Deadpikle** [comment]
Hi @mylastsong18,

Thanks for your report/message.

My gut reaction is that you haven't uploaded the .signature file or there's something wrong with your app cast validation (wrong public/private key) -- there should be more logs than what you posted that would help point to the problem. "Appcast is not valid" is shown when, well, the app cast couldn't be downloaded or parsed. The error about version information shown after that is just a false warning caused by the earlier ones. Editing your appcast version manually won't help if it's a signature verification issue.

Please do the following:

0. Try setting your `ISignatureVerifier.SecurityMode` to `Unsafe`. If things work after this, you've got a signature/verification file problem.
1. Post the FULL logs from your output, anonymized as necessary
2. Post the contents of your appcast file, anonymized as necessary
3. Make sure you can actually download your appcast from your server (try the URL in your browser)

Thanks!

**Comment by mylastsong18** [comment]
It appears to be an SSL issue which is strange cause i have another program that downloads a json file from the same server and i am able to download the appcast in a browser. I will have to play around with it and see if i can get it working. Most likely something on my end and has nothing to do with NetSparkle 

I did try the unsafe method but it didn't make a difference, i don't think the appcast is being downloaded at all due to the SSL authentication failing.

**Comment by mylastsong18** [comment]
It was indeed an SSL issue, changing TrustEverySSLConnection to true worked and got rid of the error so when i release the program it won't be an issue since it'll be a public server. Thank you!
