### ISSUE TITLE
signature verification can cause the application to run out of memory if the file is too large

### ISSUE THREAD

**Issue by emazv72** [NetSparkleUpdater/NetSparkle#268]
The signature verification of a large file (  a 500Mb executable ) throws an exception on a sample application:

```
2022-01-06 11:42:58.9488 INFO Performing signature check
2022-01-06 11:43:02.2117 INFO Error validating signature of file: Exception of type 'System.OutOfMemoryException' was thrown.;    at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Org.BouncyCastle.Crypto.Signers.Ed25519Signer.BlockUpdate(Byte[] buf, Int32 off, Int32 len) in /_/crypto/src/crypto/signers/Ed25519Signer.cs:line 54
   at NetSparkleUpdater.SignatureVerifiers.Ed25519Checker.VerifySignature(String signature, Byte[] dataToVerify)
   at NetSparkleUpdater.SignatureVerifiers.Ed25519Checker.VerifySignatureOfFile(String signature, String binaryPath)
   at NetSparkleUpdater.SparkleUpdater.OnDownloadFinished(Object sender, AsyncCompletedEventArgs e)
```

The file should be read and processed in chunks, not the whole file:

```
public ValidationResult VerifySignatureOfFile(string signature, string binaryPath)
        {
            using (Stream inputStream = File.OpenRead(binaryPath))
            {
                return VerifySignature(signature, Utilities.ConvertStreamToByteArray(inputStream));
            }
        }
```

**Comment by Deadpikle** [comment]
Hi @emazv72,

Thanks for your report.

I.....don't know if it is cryptographically possible to verify a file in chunks. I think you need the whole file to get/verify a signature. I'd recommend seeing if you can expand the memory capacity of your application, split up your downloads into multiple downloads, have your installer download the extra files, or something.

The ever-faithful Sparkle library, which this lib is based on, just reads in the whole file: https://github.com/sparkle-project/Sparkle/blob/9823892062a2c8302ac7db836628a0a210a9b395/Autoupdate/SUSignatureVerifier.m#L168

PR's and corrections welcome.

We might be able to reduce the memory when using the checker, though...

**Comment by Deadpikle** [comment]
@emazv72 I have pushed a preview version (`*-preview20220106001`) with file chunking available for Ed25519 signature reading. When SparkleUpdater read in the file, it used FileSize bytes, then when it passed those bytes to the signature verifier, the bytes are copied, which used 2x the RAM needed. This feature makes it use only 1x the amount (plus the chunk size, defaulting at 25 MB). Please try it out. I think this will save hundreds of MB of RAM in your example. See commit 30a36475cb9cdb5bc20539e8b7d6e7abfd3e88a4.

This is OPT IN behavior because technically this slows down the app and I don't want to make any breaking changes. You'll need to set the `SignatureVerifier` of the `SparkleUpdater` to something like:

```csharp
var signatureVerifier = SignatureVerifier = new Ed25519Checker(NetSparkleUpdater.Enums.SecurityMode.Strict, pubKeyBase64, readFileBeingVerifiedInChunks: true, chunkSize: 1024 * 1024 * 10);
var updater = new SparkleUpdater(appCastURL, signatureVerifier);
```

The important part is setting the `readFileBeingVerifiedInChunks` parameter.

Please let me know as soon as you can whether this helps you or not. If I don't hear from you in a while, I'll assume it does, so please speed up the process by letting me know. :)

Thank you again for filing this bug to help make this improvement.

**Comment by emazv72** [comment]
Hi @Deadpikle,

Thank you for your quick answer and patch. I've quickly tested it and it seems to work fine in my no UI - custom updater scenario.

I've made a few fixes in my reference implementation and the out of memory is gone now, maybe I'll be able to shrink the update package in the future. 

Thank you again for your help!

**Comment by Deadpikle** [comment]
Great to hear! Thanks for getting back to me so quickly. 🎉

I'll keep this issue open until the changes are in a non-preview version.

**Comment by emazv72** [comment]
Thank you for letting me find a bug myself, the OOM made me detect a non
related memory leak to fix. When we used to deal with a few Mb memory size
devices we were all more careful with resources, a long time ago... :)

Il Dom 9 Gen 2022, 02:34 Deadpikle ***@***.***> ha scritto:

**Comment by Deadpikle** [comment]
Live in NetSparkleUpdater 2.0.9, which is rolling out to NuGet now! @emazv72, I want to thank you again for your help and your very quick replies. That was a big help! (And glad we could help you fix another memory leak!)
