### ISSUE TITLE
App Cast Generator Tool version 2.0.12 is broken

### ISSUE THREAD

**Issue by GebTandon** [NetSparkleUpdater/NetSparkle#283]
The version 2.0.12 seems to be broken. The command runs fine under 2.0.11 .
Its is not able to generate appcast.xml file, fails with below error:

``` ps1
Operating System: windows
Searching: ./x
Found 1 *.msix files(s)

Error generating app cast file
Length cannot be less than zero. (Parameter 'length')

```
Here is sample command that was run 

``` ps1
netsparkle-generate-appcast -a ./netsparkle -e msix -b "./x" -o windows -n "deployer name" -f -u "https://upload.website.net/downloads/"
```

**Comment by Deadpikle** [comment]
Hi @GebTandon,

We'll look into it. Might be your product file name. Can you please let us know what the file name of your app is? An anonymized "My App Name.msix" would be fine. I think it's something to do with how the version of the app is pulled out of the file name (`-f`).

**Comment by Deadpikle** [comment]
@GebTandon,

Can you try 2.0.13, please? I found and fixed an issue here. If you are still running into issues, please let us know the file name of the app. If the app cast generating doesn't error out, please do a sanity check on the app cast output to make sure it works as it should. The `-f` functionality to get the version out of the file name was redone in 2.0.12.


Thanks!

**Comment by Deadpikle** [comment]
@GebTandon, have you been able to try out 2.0.13?

**Comment by FRvanderVeen** [comment]
I've been testing the 2.0.13 and it looks like there is a change between how -f works in 2.0.11 and 2.0.13

Given the following path:
output/1.0/file.ext

2.0.11 is able to extract version 1.0 as version
2.0.13 is not able to extract the version

Looking at the code in the comments it says that it expects the version number to be at the end of the filename, but somewhere in the path was working. Is this something that will be working again?

**Comment by Deadpikle** [comment]
Hi @FRvanderVeen,

Hmmm...`output/1.0/file.ext` working was definitely not intentional. The docs for that command said, "Determine the version from the file name" (aka not the path), so the fact that such a thing worked was, well, unintentional. Definitely never tested that case myself. Sorry about that technically breaking change, but since it was not intended to work in the first place.... 😬 

https://github.com/NetSparkleUpdater/NetSparkle/blob/63f46404f1f1069cb5fd122e1ce3ed62ac7077f4/src/NetSparkle.Tests.AppCastGenerator/AppCastMakerTests.cs#L47-L65 should give you a good idea of what we're expecting.

We would need to add an additional parameter to the app cast generator or further adjust the way this works in order to support your use case. I will file a new issue to track this request. Thanks.

**Comment by Deadpikle** [comment]
@GebTandon I'm going to assume things are working since I haven't heard back and I believe this is fixed. Please feel free to re-open if necessary. Thank you again for reporting! :)

@FRvanderVeen I re-added that functionality in the app cast generator v2.0.14, which is not working fully yet and is thus not live. Tracked in #285. Please watch that thread for updates.
