### ISSUE TITLE
Question: should you be able to control date format in UpdateAvailableWindow

### ISSUE THREAD

**Issue by FRvanderVeen** [NetSparkleUpdater/NetSparkle#334]
While looking at the contents of the UpdateAvailbleWindow my eye was caught on the following:

![image](https://user-images.githubusercontent.com/86024496/171570595-69a81b2e-31fb-404c-ac30-ec0bd210c097.png)

The date in the above format is formatted in Dutch format, while the other texts and captions on the buttons are in English. Should we be able to specify the format of the dates in the UpdateAvailableWindow? Or should they be at least in English instead of the user-configured date format?

Formatting is done here:
https://github.com/NetSparkleUpdater/NetSparkle/blob/86df223938c2c00e59a72edb2512f2f53e1a8584/src/NetSparkle/ReleaseNotesGrabber.cs#L117

**Comment by Deadpikle** [comment]
Hi @FRvanderVeen,

Good work spotting that. The short answer is that NetSparkle doesn't really do anything with localization at the moment (see #92); however, for the meantime, I have made it easier in v2.1 (rolling out now) to set the date format for release notes by adding a property to all `UIFactory` objects via the new `UIFactory.ReleaseNotesDateTimeFormat` format, which essentially gets forwarded to the `ReleaseNotesGrabber` object that's eventually created. This should at least make it easier for end users to configure this to always be in English if they desire.

I'll add a note about this to #92 and close this one as an enhancement that's done and sort-of-duplicate-about-localization. Please let me know if this should be a separate issue for some reason that I'm not thinking of right now, because I'm feeling a little tired and I may not be thinking of a reason for keeping this open 😅. 

Thank you for bringing this to my attention!
