### ISSUE TITLE
Regression - Sample HandleEventsYourself not downloading

### ISSUE THREAD

**Issue by emazv72** [NetSparkleUpdater/NetSparkle#335]
Hi,

There seems to be a regression between  2.0.9-preview20220106001 and 2.1.0.
I used code based on HandleEventsYourself, which worked with preview version and noticed the InitAndBeginDownload doesn't trigger the download.
I then downloaded and tested the original HandleEventsYourself code from tag 2.1.0, and it won't download the update.
I can't find the preview tag anymore to perform a compare. Any hint to fix?

I also checked version 2.0.9 and it worked fine, it seems to be something introduced with version 2.1.0

Regards,
Emanuele

**Comment by Deadpikle** [comment]
Hi @emazv72,

Thank you _so much_ for reporting this problem. I really appreciate it. I was able to replicate the bug that you experienced, and a fix is rolling out to NuGet via CI/CD now -- v2.1.1. 

Please note that I did find a small issue in the sample -- it is technically possible that if all the right race conditions happen and your internet is SUPER FAST, the download finished event can be called before download started, and the download started event is still called. This...could be fixed in the future, but since most will likely never run into that, but wanted to let you know.

Again, thank you!!

**Comment by emazv72** [comment]
Hi @Deadpikle,

Thank you for the quick fix, I've integrated the new release and I can confirm it works just fine, great job!
