### ISSUE TITLE
Unable to render pages properly using NetSparkle.UI.WPF or custom UI 

### ISSUE THREAD

**Issue by huangkai1994** [NetSparkleUpdater/NetSparkle#457]
I used the ui framework[WPF UI](https://github.com/lepoco/wpfui)，When I click the download/install button,An exception is thrown immediately
System.Windows.Markup.XamlParseException:““初始化“Wpf.Ui.Controls.Button”时引发了异常。”，行号为“80”，行位置为“33”。”
InvalidOperationException: 无法在各进程之间访问可冻结的“System.Windows.Media.SolidColorBrush”，因为无法冻结它。
I know this is a conflict with my UI framework, but I don't have the ability to solve this problem, who can help me? Otherwise I would have to use NetSparkle.UI.winform

**Comment by Deadpikle** [comment]
Hi @huangkai1994,

Actually, I think based on that exception, this should be fixable. Instead of using the WPF UI, link your application to the main NetSparkleUpdater repository. Then, copy in the WPF UI files (as a base) and adjust them as necessary to compile and work with your UI library that you're using. Then you can just reference that UI factory instead of the WPF one.

I do something similar in one of my own proprietary applications where I just needed to tweak the UI a bit for that app's use case, where I just copied in the files from this repository into my own project and then tweaked as needed:

<img width="290" alt="Screen Shot 2023-05-31 at 2 07 17 PM" src="https://github.com/NetSparkleUpdater/NetSparkle/assets/5092399/b738ca8a-a6b8-4230-a86e-7a9701ddb1bc">

That being said, um, looks like some brush just needs to be frozen somewhere in the main framework OR you shouldn't run WPF on the backend thread. Try setting `ShowsUIOnMainThread` to `true`.

Another thing that would help in solving this is a reproducible test case.

Thanks!

**Comment by huangkai1994** [comment]
Now I can solve my problem By set ShowsUIOnMainThread = true。
I found a new problem in ReleaseNotesGrabber class DownloadReleaseNotes method，Garbled characters are returned when the file content is in Chinese，Although I could copy the source code and add HttpClientHandler to HttpClient to solve the problem, this would not be the best solution

**Comment by Deadpikle** [comment]
The original problem is because of https://github.com/lepoco/wpfui/issues/594.

`ReleaseNotesGrabber`: Don't copy the whole source code. You can just create your own `ReleaseNotesGrabber` subclass to pull things as UTF-8. Something like:

```csharp
public class MyReleaseNotesGrabber : ReleaseNotesGrabber
    {
        public MyReleaseNotesGrabber(string releaseNotesTemplate, string htmlHeadAddition, SparkleUpdater sparkle) : base(releaseNotesTemplate, htmlHeadAddition, sparkle)
        {
        }

        protected override async Task<string> DownloadReleaseNotes(string link, CancellationToken cancellationToken, SparkleUpdater sparkle)
        {
            try
            {

                var httpClient = CreateHttpClient();
                using (cancellationToken.Register(() => httpClient.CancelPendingRequests()))
                {
                    using (HttpResponseMessage response = await httpClient.GetAsync(link))
                    {
                        var byteArray = await response.Content.ReadAsByteArrayAsync();
                        var result = Encoding.UTF8.GetString(byteArray, 0, byteArray.Length);
                        return result;
                    }
                }
            }
            catch (WebException ex)
            {
                sparkle.LogWriter.PrintMessage("Cannot download release notes from {0} because {1}", link, ex.Message);
                return "";
            }
        }
    }

// ...

var uiFactory = new NetSparkleUpdater.UI.WPF.UIFactory(...);
_sparkle = new SparkleUpdater("...", new DSAChecker(Enums.SecurityMode.Strict))
{
    ShowsUIOnMainThread = true,
};
uiFactory.ReleaseNotesGrabberOverride = new MyReleaseNotesGrabber(uiFactory.ReleaseNotesHTMLTemplate, uiFactory.AdditionalReleaseNotesHeaderHTML, _sparkle);
_sparkle.UIFactory = uiFactory;
// ...
_sparkle.StartLoop(true, true);
```

**Comment by huangkai1994** [comment]
Thank you. That solves my problem

**Comment by Deadpikle** [comment]
Great! Glad to hear. :)
