### ISSUE TITLE
Provide version as a command line parameter

### ISSUE THREAD

**Issue by christophwille** [NetSparkleUpdater/NetSparkle#459]
#306 I too have an msi - but instead of naming the file in a special way, why not simply let me specify the version as a parameter?

**Comment by Deadpikle** [comment]
Added in App Cast Generate v2.2.2 (...which should have been labeled 2.3.0, since this was a feature change and not a bug fix, but I goofed on that).

There is the caveat that only 1 version can be set and if the generator finds more than 1 binary without a version, app cast generation fails. But for some use cases where there is always "the latest version" and/or you are reparsing an existing app cast, that will probably be fine. (This is why I was hesitant to add it before. But looking at it again I decided it was worth it for some use cases.)

Thanks!

Edit: Use via the `--file-version` parameter.
