### ISSUE TITLE
Question: Release notes

### ISSUE THREAD

**Issue by christophwille** [NetSparkleUpdater/NetSparkle#465]
I am having a hard time attaching the readme notes:

`netsparkle-generate-appcast -n "ILSpy" -a ./output -e msi -b ./ -o windows -f true -u https://github.com/icsharpcode/ILSpy/releases/tag/v8.0 --description-tag ".NET Decompiler" --key-path ./signingkeys --change-log-path ./changelogs`

In that changelogs subfolder, I have an "ILSpy 8.0.0.7400.md", however, I doesn't get picked up and there is no indication as to what I might be doing wrong (if I screw up eg --key-path, I get a warning):

```
Operating System: windows
Searching: ./
Found 1 *.msi files(s)

Found a binary with version 8.0.0.7400
Writing app cast to ./output\appcast.xml
```

**Comment by Deadpikle** [comment]
Hi,

The issue is that the app cast gen only looks for change logs in the format `{Version}.md`, not `{AppName} {Version}.md`. I have just added another param to the app cast generator, `--change-log-name-prefix`, so you can use `--change-log-name-prefix "ILSpy"` and the format you've specified above for change log file names. This will roll out soon.

Thanks!

(For future reference, here was the applicable code before changes.)

https://github.com/NetSparkleUpdater/NetSparkle/blob/b4e3f6a050d83186316a8a137e58b72c076c565b/src/NetSparkle.Tools.AppCastGenerator/AppCastMaker.cs#L206-L208

**Comment by christophwille** [comment]
![image](https://github.com/NetSparkleUpdater/NetSparkle/assets/344208/0ba5f748-4b50-48cd-bdad-6f20bf2c28c2)

that is what triggered me naming the file that way. So the README/param doc is misleading.

**Comment by Deadpikle** [comment]
Ahh....So it is. Sorry about that. Will update that too.
