### ISSUE TITLE
Window Owner for WPF Software Update Dialog

### ISSUE THREAD

**Issue by christophwille** [NetSparkleUpdater/NetSparkle#469]
Is it intentional that this dialog is not modal by default? What just happened to me is that I closed the app and the update dialog stayed around - without any indication of it in the task bar (it shows in Alt-Tab).

**Comment by Deadpikle** [comment]
Intentional for it to stay open? Yes -- if the user has slow internet and wants to close the main software while their connection slowly chugs away at the update, I would think that would be a thing users would want. (The original Sparkle handles this the same way, based on a quick re-test.)

Not showing in the taskbar? Sounds like a bug to me. I see `ShowInTaskbar` is set to `false` for the toast messages, but it's not set elsewhere, so not sure right off what's going on there. Thanks for the report.

**Comment by Deadpikle** [comment]
This is caused by your `DialogWindow` style in ILSpy: https://github.com/icsharpcode/ILSpy/blob/bdb32356635f2fdc66b9dfb8cd028675cce47883/ILSpy/App.xaml#L11

`ShowInTaskbar` is set to false, so the update window isn't showing in the task bar.

**Comment by Deadpikle** [comment]
Upon further review of the "let's close the main window such that we can still run the update regardless" thing, a bug has come up:

1. Set `ShowsUIOnMainThread` to `false`
2. Start sample
3. Close main window
4. Update window no longer responds to button clicks or anything since the marshaling to the UI thread func now hangs/fails which is definitely not the intended behavior

So...this part of things has been broken/not working for awhile. Not sure if this is a recent .NET 7 issue or if this is something that was missed a long time ago.

I'll readily admit that the `ShowsUIOnMainThread` thing is a bit of a mess.

**Comment by Deadpikle** [comment]
Threading issues moved to #470

**Comment by Deadpikle** [comment]
Bug I noted in a comment above is done/gone; `ShowsUIOnMainThread` is gone completely. (#609)

Note that for WinForms apps, closing the main form will currently close SparkleUpdater forms unless the user handles threads/things themselves via `SparkleUpdater` events; see the `NetSparkle.Samples.Forms.Multithread` sample to see how to handle that. WPF/Avalonia still functions as before -- `SparkleUpdater` windows will stay open even if the main window is closed (unless the user has some special logic implemented on their app's end).
