### ISSUE TITLE
Question about 2.51

### ISSUE THREAD

**Issue by AlexSanchezN** [NetSparkleUpdater/NetSparkle#568]
There seems not to be a package for version 2.51 in nuget. Latest I could find is 2.30
Are versions above 2.30 preview? Or are ready for production?

Thanks for your time and the library!

**Comment by Deadpikle** [comment]
Hi @AlexSanchezN,

There is not a 2.5.1 (or 2.51) for the main library. That version is just for the app cast generator tool, which has its own version numbering and does not match the core library in terms of version numbers (since it can have its own features and bug fixes, etc.). The latest stable version for the core library is 2.3.0, and everything newer than that for the core library is 3.0 previews for now.

Does that help?

**Comment by AlexSanchezN** [comment]
It helps a lot.
I will use 2.3.0 for production
 
Thanks!
