### ISSUE TITLE
Broken Version Number Detection in AppCastGenerator

### ISSUE THREAD

**Issue by eminsenay** [NetSparkleUpdater/NetSparkle#588]
I'm using AppCastGenerator with the following options:

```
netsparkle-generate-appcast --key-path .\Setup\netsparkle\ -a .\Setup\ -b .\Setup\ -u <pathgoeshere> -p ./ReleaseNotes/Windows/ -n "MyAppName" -f true
```

The setup file can be found under the given directory with a name like "appsetup-2.10.1.exe".

I realized that the AppCastGenerator incorrectly detects the version name as "10.1" instead of "2.10.1":

```
Operating System: windows
Searching: .\Setup\
Found 1 *.exe files(s)

Found a binary with version 10.1
Writing app cast to .\Setup\appcast.xml
Wrote .\Setup\appcast.xml.signature
```

I checked the sources and found out that the bug is introduced with the commit f77a4ef2.

**Comment by Deadpikle** [comment]
@eminsenay Thanks for the report! I can confirm that this is broken, and we'll need to get that fixed. Looks like an issue where the `-` confuses things due to the semantic versioning stuff.

In the meantime, you can either:

* Use an older version of the app cast generator
* Replace the `-` with a `_` in the file name
* Use a ` ` (space) instead of `-`

**Comment by Deadpikle** [comment]
All fixed! Thank you for your detailed report. v2.6.1 of the app cast generator will be rolling out shortly.
